name: deploy-to-pages

on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          mkdir -p tmp/${{ github.head_ref }}
          cp -r src/* tmp/${{ github.head_ref }}/
          git checkout gh-pages
          cp -r tmp/${{ github.head_ref }} dist/
          rm -r tmp
          git add .
          git commit -m "Update doc. branch:${{github.head_ref}}, sha:${{github.sha}}"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
